### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by Cederik-Edorble** [MakeInBelgium/ElkeLeerlingOnline#15]
We hebben best wat aanvragen nu, een filter functie zou goed zijn.

Ook aan het praten met stad antwerpen, die zouden bvb willen kunnen verwijzen naar een pagina met enkel provincie antwerpen

**Comment by laurensdeb** [comment]
De filtering zit er in de repo in, enige probleem is dat de caching op niveau van de CDN ervoor zorgt dat de filters nog niet getoond worden op de site. Dit zou binnen enkele uren opgelost moeten zijn.
